### ISSUE TITLE
Add rel canonical tag

### ISSUE THREAD

**Issue by johnkramlich** [redvanworkshop/website#23]
#### Overview:

Setup a rel canonical tag so that two versions of a url, e.g. https://dev.redvanworkshop.com/services.html and https://dev.redvanworkshop.com/services are considered the same content and will not be flagged as duplicate content by Google, or have backlink link juice split between the two versions.  

More information here:  https://yoast.com/rel-canonical/

#### Acceptance Criteria:

- Choose a version that we consider the real versions, i.e. URLs without the HTML extension like https://dev.redvanworkshop.com/services
- Ensure that https://dev.redvanworkshop.com/services.html has a rel canonical tag that points to https://dev.redvanworkshop.com/services

**Comment by manifestinteractive** [comment]
I fixed this on the Nginx level, as the careers.html page was the only one that previously existed that could confuse search engines.
