### ISSUE TITLE
MailChimp Contact Request Email - Styling Needed

### ISSUE THREAD

**Issue by nancyhstorey** [redvanworkshop/website#30]
#### Overview:

Email format isn't consistent with the style of the website. It looks very system-generated as opposed to "pretty".  It also doesn't really communicate that you are confirming your email address so we can get back in touch with them, rather it looks like we are requesting they subscribe to something. This could cause people NOT to confirm because they don't want to start getting emails.

#### Acceptance Criteria:

- [x] Email Subject is "personal" as opposed to "robotic" clearly communicating their request to be contacted has been received.

- [x] Email Pre-Header clearly communicates required action in order to ensure they will be contacted, or a "thank you" for their inquiry.

- [x] Email Header is "personal"; doesn't sound like a system generated email using database field names

- [x] style looks more like a "marketing" email that is consistent with website/brand

- [x] Email communicates to user their request was received

- [x] Email communicates to user what action is needed to confirm their address in order to reassure them they will be getting a response (if they are submitting request to be contacted, don't reply with a "confirm your subscription" message; this is confusing).

#### Steps to Duplicate _( required for bug reports )_:

Complete and submit 'Contact Us' form.

#### System Info _( required for bug reports )_:

N/A

#### Relevant Documentation _( optional )_

**Email Subject and Pre-Header**

![subject and preheader](https://user-images.githubusercontent.com/46008491/50290123-54410780-0430-11e9-8ea7-971ea1ead98f.png)

**Email**

<img width="1214" alt="contact email-needs styling and re-wording" src="https://user-images.githubusercontent.com/46008491/50289927-cb29d080-042f-11e9-9310-7bf367391f10.png">

**Comment by manifestinteractive** [comment]
Attaching new styles

![1-email-confirm](https://user-images.githubusercontent.com/508411/50369181-2c03f680-055f-11e9-9c8f-eae17777216b.png)
![2-email-confirmed](https://user-images.githubusercontent.com/508411/50369182-2c03f680-055f-11e9-9adf-8f61e0bcbd1a.png)
![3-website-confirm](https://user-images.githubusercontent.com/508411/50369183-2c03f680-055f-11e9-98f9-6121051aa6f3.png)
![4-website-confirmed](https://user-images.githubusercontent.com/508411/50369184-2c03f680-055f-11e9-830b-7fc307bcc517.png)
