### ISSUE TITLE
IE - Driving Game Not Launching 

### ISSUE THREAD

**Issue by nancyhstorey** [redvanworkshop/website#32]
#### Overview:

Driving game modal won't open when using IE (not sure about Edge; Edge has other issues that will be logged in a separate ticket)

#### Acceptance Criteria:

Triple clicking on Red Van in the footer launches the driving game in a modal.

#### Steps to Duplicate _( required for bug reports )_:

Triple click on Red Van in footer

#### System Info _( required for bug reports )_:

Windows 10, IE 11

#### Relevant Documentation _( optional )_

N/A

**Comment by manifestinteractive** [comment]
So this is actually a happy accident.  It looks like older version of IE do not support tracking the number of clicks on an element.  It also appears that the Game itself does not work very well either on IE, so I am actually going to leave this as it is, as the browsers the triple click works on are the ones that can actually play the game correctly.
