### ISSUE TITLE
Edge - Global Footer Rendering Issue / All Pages

### ISSUE THREAD

**Issue by nancyhstorey** [redvanworkshop/website#33]
#### Overview:

The footer displays static and "stretched" from about the middle of the page to the bottom of the page, with the Van displaying right about at the "fold"; followed by each layer of the footer landscape displayed separately until you reach the bottom of the page.

#### Acceptance Criteria:

Global footer is "animated" and expands as you approach the bottom of the page, revealing the background/landscape. 

#### Steps to Duplicate _( required for bug reports )_:

Display any page using Edge browser and scroll down the page; observe footer contents starting at right about at the fold.

Note: The Home page and Services page consistently display incorrectly, but the Clients and Careers pages will intermittently display the layered footer correctly at the bottom of the page, but without using any animation.

#### System Info _( required for bug reports )_:

Windows 10, IE 11

#### Relevant Documentation _( optional )_

**Home Page**
![edge - home page](https://user-images.githubusercontent.com/46008491/50292523-f368fd80-0436-11e9-9c96-876ccbbb1a10.png)

**Services Page**
![edge services page](https://user-images.githubusercontent.com/46008491/50292676-53f83a80-0437-11e9-8f83-fec67be91c27.png)

**Clients Page**
![edge clients page](https://user-images.githubusercontent.com/46008491/50292689-5e1a3900-0437-11e9-9ad0-eea0950825b6.png)

**Comment by manifestinteractive** [comment]
This will be pushed up in the next release.  I added some logic to just skip the parallax rendering altogether for IE since it is so buggy.
