### ISSUE TITLE
MailChimp Newletter Sign Up Page Styling

### ISSUE THREAD

**Issue by nancyhstorey** [redvanworkshop/website#34]
#### Overview:

When select 'Join Newsletter' from Home Page, you are redirected to a sign up form. This page / form still has the old RedVan website styling; it should match the new site style.

#### Acceptance Criteria:

Newsletter Sign Up page has same look and feel as the Red Van Workshop website.

#### Steps to Duplicate _( required for bug reports )_:

From home page, select 'Join Newsletter' CTA

#### System Info _( required for bug reports )_:

N/A

#### Relevant Documentation _( optional )_

**Sign Up Page**

![newsletter sign up page](https://user-images.githubusercontent.com/46008491/50293132-763e8800-0438-11e9-996a-df1ee98869b1.png)

**Comment by manifestinteractive** [comment]
( sorry, incorrectly closed this one )

**Comment by manifestinteractive** [comment]
Closing this out since it has sat for over a year and is not really a priority anymore.
