### ISSUE TITLE
Review/Improve Experience After Signing Up for Newsletter from MailChimp

### ISSUE THREAD

**Issue by nancyhstorey** [redvanworkshop/website#37]
#### Overview:

Currently, when you select 'Join Newsletter' from the homepage, you are redirected to a page hosted by MailChimp to sign up.  Once you have entered your information and submitted you are redirected to the RedVanWorkshop home page.  Is there any way to return a message indicating their request has been submitted and that they will be getting an email to confirm their email address? 

Note: I was also redirected to the current, live Red Van site rather than being redirected to the dev site... This seems like it would be expected but wanted to mention it in case you did have logic in place to address this, I just didn't hit it due to prod redirect.

#### Acceptance Criteria:

Messaging that their newsletter sign up was successful and information about what to expect next.

#### Steps to Duplicate _( required for bug reports )_:

1. From home page select 'Join Newsletter'
2. Redirected to Mailchimp for entry of required info
3. Enter required information and submit request
4. Redirected to Red Van home page

#### System Info _( required for bug reports )_:

N/A

**Comment by manifestinteractive** [comment]
Closing this out since it has sat for over a year and is not really a priority anymore.
