### ISSUE TITLE
Fruit Logo 

### ISSUE THREAD

**Issue by johnnyv786** [redvanworkshop/website#40]
#### Overview:

On Case Study page, Fruit of the loom logo is wrong, brought up by client

#### Acceptance Criteria:

Correct Fruit of the Loom corporate logo ( [logo-color.svg.zip](https://github.com/redvanworkshop/website/files/3031668/logo-color.svg.zip) ) added in place of Active wear logo on the following pages:

* https://redvanworkshop.com/clients
* https://redvanworkshop.com/salesforce-commerce-cloud/fruit-of-the-loom

**Comment by manifestinteractive** [comment]
This is has been fixed and deployed in v1.0.5
